// CART
export const CART_SET_ID = 'CART_SET_ID'
export const CART_SET_REF = 'CART_SET_REF'
export const CART_ADD_ITEM = 'CART_ADD_ITEM'
export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM'
export const CART_EDIT_ITEM = 'CART_EDIT_ITEM'
export const CART_CLEAR = 'CART_CLEAR'
export const SET_CART = 'SET_CART'
export const CART_CHANGED = 'CART_CHANGED'
export const SET_CART_STATUS = 'SET_CART_STATUS'

// CLIENT
export const CLEAR_CLIENT = 'CLEAR_CLIENT'
export const SET_CLIENT = 'SET_CLIENT'
export const SET_CLIENT_PROP = 'SET_CLIENT_PROP'

// Products
export const ADD_PRODUCT = 'ADD_PRODUCT'
export const SET_PRODUCT_BRANDS = 'SET_PRODUCT_BRANDS'
export const SET_CURRENT_ITEM = 'SET_CURRENT_ITEM'
export const SET_CURRENT_ITEM_PROP = 'SET_CURRENT_ITEM_PROP'

// Discounts
export const SET_DISCOUNTS = 'SET_DISCOUNTS'
export const SET_CURRENT_DISCOUNT = 'SET_CURRENT_DISCOUNT'

// Cloud
export const ADD_CLOUD = 'ADD_CLOUD'
export const SET_CLOUD_PROVIDERS = 'SET_CLOUD_PROVIDERS'
export const SET_CURRENT_CLOUD_SELECTION = 'SET_CURRENT_CLOUD_SELECTION'

// FORM
export const SET_PURCHASE_SUCCESS = 'SET_PURCHASE_SUCCESS'
export const CLEAR_CURRENT_FORM_STEP = 'CLEAR_CURRENT_FORM_STEP'
export const SET_CURRENT_FORM_STEP = 'SET_CURRENT_FORM_STEP'
export const SET_ALLOW_FORM_SUBMIT = 'SET_ALLOW_FORM_SUBMIT'
export const SET_ACCEPTED_TERMS = 'SET_ACCEPTED_TERMS'

// Plan Info
export const SET_SUPPORT_MONTHS = 'SET_SUPPORT_MONTHS'
export const SET_CURRENT_PLAN = 'SET_CURRENT_PLAN'
export const SET_CATEGORY_MULTIPLIER = 'SET_CATEGORY_MULTIPLIER'

// PDFS
export const SET_INVOICE_PDF = 'SET_INVOICE_PDF'
export const SET_ESTIMATE_PDF = 'SET_ESTIMATE_PDF'
export const SET_ESTIMATE_ID = 'SET_ESTIMATE_ID'

// Notifications
export const ADD_NOTIFICATION = 'ADD_NOTIFICATION'
export const REMOVE_NOTIFICATION = 'REMOVE_NOTIFICATION'

// Payment
export const SET_STRIPE = 'SET_STRIPE'
export const SET_PAYMENT_OBJECT = 'SET_PAYMENT_OBJECT'
export const SET_PAYMENT_PROCESSING = 'SET_PAYMENT_PROCESSING'
export const SET_PAYMENT_TOKEN = 'SET_PAYMENT_TOKEN'
export const SET_PAYMENT_PROP = 'SET_PAYMENT_PROP'
