# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-28 22:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0063_cloud_quantity_multiplier'),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=128)),
                ('bank_id', models.CharField(blank=True, max_length=128)),
                ('bank_verified', models.BooleanField(default=False)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='support.Client')),
            ],
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
        migrations.AddField(
            model_name='payment',
            name='amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='payment',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='support.Cart'),
        ),
        migrations.AddField(
            model_name='payment',
            name='client',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='support.Client'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('creditcard', 'Credit Card'), ('achplaid', 'Bank ACH - Plaid'), ('achstripe', 'Bank ACH - Stripe'), ('paypal', 'Paypal'), ('po', 'Purchase Order')], default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='secondary_token',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='payment',
            name='token',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receipt',
            name='amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='receipt',
            name='discount_percentage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='receipt',
            name='payment_type',
            field=models.CharField(choices=[('creditcard', 'Credit Card'), ('achplaid', 'Bank ACH - Plaid'), ('achstripe', 'Bank ACH - Stripe'), ('paypal', 'Paypal'), ('po', 'Purchase Order')], default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receipt',
            name='subscription',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='support.Subscription'),
            preserve_default=False,
        ),
    ]
