# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-29 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_stripeclient_bank_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stripeclient',
            name='bank_type',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
