# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-29 23:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_auto_20170929_1147'),
        ('payment', '0004_payment_token_expired'),
    ]

    operations = [
    ]
