# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-12 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FreshbooksAuth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=150)),
                ('auth', models.CharField(max_length=150)),
                ('refresh', models.CharField(max_length=150)),
                ('expires', models.DateTimeField()),
            ],
        ),
    ]
