# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 19:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0004_auto_20170714_1749'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(blank=True, max_length=128)),
                ('device_age', models.IntegerField(default=0)),
                ('additional_info', models.TextField(blank=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='support.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Cloud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('website', models.CharField(max_length=128)),
                ('price_modifier', models.FloatField(default=0.0)),
                ('color', models.CharField(blank=True, max_length=64)),
                ('image', models.ImageField(blank=True, upload_to='images/cloud/')),
            ],
        ),
        migrations.AddField(
            model_name='clientproduct',
            name='cloud',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='support.Cloud'),
        ),
        migrations.AddField(
            model_name='clientproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='support.Product'),
        ),
    ]
