# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0006_auto_20170727_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('srvr', 'Servers'), ('strg', 'Storage'), ('frwl', 'Firewalls'), ('netswch', 'Network Switches')], default='srvr', max_length=32),
            preserve_default=False,
        ),
    ]
