# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 00:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0009_auto_20170801_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientproduct',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='support.Client'),
        ),
    ]
