# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 01:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0010_auto_20170803_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientproduct',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='support.Product'),
        ),
    ]
