# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 01:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0011_auto_20170803_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientproduct',
            name='brand',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='clientproduct',
            name='model',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
