# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 01:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0013_remove_clientproduct_cloud'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='date_subscription_begin',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscription',
            name='length',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='subscription',
            name='products',
            field=models.ManyToManyField(to='support.ClientProduct'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(to='support.ClientProduct'),
        ),
    ]
