# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 04:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0014_auto_20170803_1831'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='date_subscription_begin',
            new_name='date_begin',
        ),
    ]
