# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 22:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0016_cart_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='plan',
            field=models.CharField(choices=[('silver', 'Silver'), ('gold', 'Gold'), ('black', 'Black')], max_length=32),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.CharField(choices=[('silver', 'Silver'), ('gold', 'Gold'), ('black', 'Black')], max_length=32),
        ),
    ]
