# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0018_auto_20170807_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientproduct',
            name='serial_number',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
