# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 23:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0020_auto_20170807_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='length',
            field=models.FloatField(default=0.5),
        ),
    ]
