# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 00:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0021_cart_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, to='support.ClientProduct'),
        ),
    ]
