# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 05:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0022_auto_20170807_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cloud',
            field=models.ManyToManyField(blank=True, to='support.Cloud'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='products',
            field=models.ManyToManyField(blank=True, to='support.ClientProduct'),
        ),
    ]
