# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0023_auto_20170807_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='dynamicscrm_id',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='client',
            name='freshbooks_id',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
