# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0027_remove_product_with_cloud'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='yearly_tax',
            field=models.FloatField(default=0.1),
        ),
    ]
