# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 22:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0028_productcategory_yearly_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='short_name',
            field=models.CharField(default='', max_length=16),
            preserve_default=False,
        ),
    ]
