# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-12 07:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0029_plan_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='freshbooks_id',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
