# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-12 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0030_cart_freshbooks_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cloud',
            name='price_modifier',
        ),
        migrations.AddField(
            model_name='cloud',
            name='price_multiplier',
            field=models.FloatField(default=1.0),
        ),
    ]
