# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-12 08:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0031_auto_20170812_0045'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_threshold', models.FloatField(default=0.0)),
                ('discount_percent', models.FloatField(default=0.1)),
            ],
        ),
    ]
