# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-14 23:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0032_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstimateText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='support.ProductCategory')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='support.Plan')),
            ],
        ),
    ]
