# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-14 23:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0033_estimatetext'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimatetext',
            name='item',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
