# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-14 23:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0034_estimatetext_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimatetext',
            name='cloud',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='support.Cloud'),
        ),
    ]
