# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-16 01:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0036_auto_20170814_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='approved',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='company',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.CharField(max_length=128),
        ),
    ]
