# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-16 03:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0037_auto_20170815_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='replaced',
            field=models.BooleanField(default=False),
        ),
    ]
