# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-17 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0038_cart_replaced'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='release',
            field=models.DateField(blank=True, null=True),
        ),
    ]
