# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-23 20:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0040_auto_20170818_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='support.Cart'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='cloud',
            field=models.ManyToManyField(blank=True, null=True, to='support.Cloud'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='discount_percent',
            field=models.FloatField(default=0.0),
        ),
    ]
