# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-05 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0042_auto_20170823_1327'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnknownProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('serial_number', models.CharField(blank=True, max_length=128, null=True)),
                ('device_age', models.IntegerField(default=0)),
                ('additional_info', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='approved',
        ),
    ]
