# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-05 23:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0043_auto_20170905_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='unknownproduct',
            name='client',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='support.Client'),
            preserve_default=False,
        ),
    ]
