# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-12 21:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0045_freshbooksauth'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FreshbooksAuth',
        ),
    ]
