# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-13 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0046_delete_freshbooksauth'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='partner_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='product',
            name='retail_price',
            field=models.FloatField(default=0.0),
        ),
    ]
