# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-14 01:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0047_auto_20170913_1416'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='freshbooks_id',
            new_name='freshbooks_estimate_id',
        ),
        migrations.AddField(
            model_name='cart',
            name='freshbooks_estimate_num',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
