# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-14 01:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0048_auto_20170913_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='freshbooks_invoice_num',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
