# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-15 22:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0049_subscription_freshbooks_invoice_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
