# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-15 23:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0050_client_stripe_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='stripe_bank_id',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
