# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-20 20:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0052_auto_20170920_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='support.Cart'),
        ),
    ]
