# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-22 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0054_auto_20170921_1238'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cloudaddon',
            old_name='name',
            new_name='category',
        ),
        migrations.AddField(
            model_name='cloudaddon',
            name='is_price_final',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cloudaddon',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='cloudaddon',
            name='sub_category',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
