# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-22 21:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0055_auto_20170922_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloudaddon',
            name='cloud_backup_name',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='cloudaddon',
            name='cloud',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='support.Cloud'),
        ),
    ]
