# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-25 22:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0056_auto_20170922_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientproduct',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
