# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-25 22:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0057_clientproduct_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientproduct',
            name='quantity',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
