# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-25 23:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0058_auto_20170925_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloud',
            name='price_black',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='cloud',
            name='price_gold',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='cloud',
            name='price_silver',
            field=models.FloatField(default=1.0),
        ),
    ]
