# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-26 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0059_auto_20170925_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='unknownproduct',
            name='release',
            field=models.DateField(blank=True, null=True),
        ),
    ]
