# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-26 23:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0061_auto_20170926_1346'),
        ('support', '0060_auto_20170926_1339'),
    ]

    operations = [
    ]
