# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-27 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0062_merge_20170926_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloud',
            name='quantity_multiplier',
            field=models.FloatField(default=0.1),
        ),
    ]
