# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-27 22:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0063_cloud_quantity_multiplier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='cart',
        ),
        migrations.AddField(
            model_name='cart',
            name='submitted_for_verification',
            field=models.BooleanField(default=False),
        ),
    ]
