# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-27 22:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0064_auto_20170927_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='submitted_for_verification',
            field=models.NullBooleanField(default=False),
        ),
    ]
