# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-28 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0066_remove_subscription_cloud'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='submitted_for_verification',
        ),
        migrations.AddField(
            model_name='cart',
            name='cart_status',
            field=models.CharField(choices=[('awaiting_product_approval', 'Awaiting Product Approval'), ('awaiting_ach_verification', 'Awaiting ACH Verification'), ('awaiting_po_approval', 'Awaiting Product Order Approval'), ('none', 'None')], default='none', max_length=32),
        ),
    ]
