# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-28 22:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0067_auto_20170928_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unknownproduct',
            name='additional_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
