# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('position', models.CharField(max_length=64)),
                ('location', models.CharField(max_length=128)),
                ('country', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('responsibilities', models.TextField()),
                ('requirements', models.TextField()),
                ('qualifications', models.TextField()),
                ('benefits', models.CharField(blank=True, max_length=128)),
                ('salary', models.CharField(blank=True, max_length=64)),
                ('job_type', models.CharField(blank=True, max_length=64)),
            ],
        ),
    ]
