# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_remove_application_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
