# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_job_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='linkedin',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
